import type { Metadata } from "next";
import {inconsolata} from "../ui/fonts/fonts"
import "./globals.css"

export const metadata: Metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className={`${inconsolata.className} bg-main-bg`}>{children}</body>
    </html>
  );
}
